version: '3'

services:

  mongo:
    image: mongo  
    volumes:
      - mongodb_data:/data/db

  app:
    image: index.docker.io/bernardovale/todo-app:$APP_VERSION
    links: 
      - mongo
    environment: 
      - MONGODB_HOST=mongo
      - APP_ENV=production
      - APP_VERSION=$APP_VERSION
    ports:
      - 8001:8001
    working_dir: /usr/src/app
    command: python run.py

volumes:
  mongodb_data: